/*
 * Below is the copyright agreement for IMCJava.
 * 
 * Copyright (c) 2010-2013, Laboratório de Sistemas e Tecnologia Subaquática
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     - Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     - Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     - Neither the names of IMC, LSTS, IMCJava nor the names of its 
 *       contributors may be used to endorse or promote products derived from 
 *       this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL LABORATORIO DE SISTEMAS E TECNOLOGIA SUBAQUATICA
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE 
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *  
 *                                                                             $:
 */

// Source generated by IMCJava from IMC version 5.4.x
package pt.lsts.imc;

/**
 *  IMC Message Asset Position (876)<br/>
 */

public class AssetPosition extends IMCMessage {

	public static final int ID_STATIC = 876;

	public enum POS_TYPE {
		DESIRED(1),
		TARGET(2);

		protected long value;

		public long value() {
			return value;
		}

		POS_TYPE(long value) {
			this.value = value;
		}
	}

	public AssetPosition() {
		super(ID_STATIC);
	}

	public AssetPosition(IMCDefinition defs) {
		super(defs, ID_STATIC);
	}

	public static AssetPosition create(Object... values) {
		AssetPosition m = new AssetPosition();
		for (int i = 0; i < values.length-1; i+= 2)
			m.setValue(values[i].toString(), values[i+1]);
		return m;
	}

	public static AssetPosition clone(IMCMessage msg) throws Exception {

		AssetPosition m = new AssetPosition();
		if (msg == null)
			return m;
		if(msg.definitions != m.definitions){
			msg = msg.cloneMessage();
			IMCUtil.updateMessage(msg, m.definitions);
		}
		else if (msg.getMgid()!=m.getMgid())
			throw new Exception("Argument "+msg.getAbbrev()+" is incompatible with message "+m.getAbbrev());

		m.getHeader().values.putAll(msg.getHeader().values);
		m.values.putAll(msg.values);
		return m;
	}

	public AssetPosition(POS_TYPE pos_type) {
		super(ID_STATIC);
		setPosType(pos_type);
	}

	/**
	 *  @return Position Type (enumerated) - uint8_t
	 */
	public POS_TYPE getPosType() {
		try {
			POS_TYPE o = POS_TYPE.valueOf(getMessageType().getFieldPossibleValues("pos_type").get(getLong("pos_type")));
			return o;
		}
		catch (Exception e) {
			return null;
		}
	}

	/**
	 *  @param pos_type Position Type (enumerated)
	 */
	public void setPosType(POS_TYPE pos_type) {
		values.put("pos_type", pos_type.value());
	}

	/**
	 *  @param pos_type Position Type (as a String)
	 */
	public void setPosType(String pos_type) {
		setValue("pos_type", pos_type);
	}

	/**
	 *  @param pos_type Position Type (integer value)
	 */
	public void setPosType(short pos_type) {
		setValue("pos_type", pos_type);
	}

}
