/*
 * Below is the copyright agreement for IMCJava.
 * 
 * Copyright (c) 2010-2013, Laboratório de Sistemas e Tecnologia Subaquática
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     - Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     - Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     - Neither the names of IMC, LSTS, IMCJava nor the names of its 
 *       contributors may be used to endorse or promote products derived from 
 *       this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL LABORATORIO DE SISTEMAS E TECNOLOGIA SUBAQUATICA
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE 
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *  
 *                                                                             $:
 */

// Source generated by IMCJava from IMC version 5.4.x
package pt.lsts.imc;

/**
 *  IMC Message Iridium Subscription (875)<br/>
 */

public class IridiumSubscription extends IMCMessage {

	public static final int ID_STATIC = 875;

	public enum REQ_TYPE {
		ACTIVATE(1),
		DEACTIVATE(2);

		protected long value;

		public long value() {
			return value;
		}

		REQ_TYPE(long value) {
			this.value = value;
		}
	}

	public IridiumSubscription() {
		super(ID_STATIC);
	}

	public IridiumSubscription(IMCDefinition defs) {
		super(defs, ID_STATIC);
	}

	public static IridiumSubscription create(Object... values) {
		IridiumSubscription m = new IridiumSubscription();
		for (int i = 0; i < values.length-1; i+= 2)
			m.setValue(values[i].toString(), values[i+1]);
		return m;
	}

	public static IridiumSubscription clone(IMCMessage msg) throws Exception {

		IridiumSubscription m = new IridiumSubscription();
		if (msg == null)
			return m;
		if(msg.definitions != m.definitions){
			msg = msg.cloneMessage();
			IMCUtil.updateMessage(msg, m.definitions);
		}
		else if (msg.getMgid()!=m.getMgid())
			throw new Exception("Argument "+msg.getAbbrev()+" is incompatible with message "+m.getAbbrev());

		m.getHeader().values.putAll(msg.getHeader().values);
		m.values.putAll(msg.values);
		return m;
	}

	public IridiumSubscription(REQ_TYPE req_type) {
		super(ID_STATIC);
		setReqType(req_type);
	}

	/**
	 *  @return Request Type (enumerated) - uint8_t
	 */
	public REQ_TYPE getReqType() {
		try {
			REQ_TYPE o = REQ_TYPE.valueOf(getMessageType().getFieldPossibleValues("req_type").get(getLong("req_type")));
			return o;
		}
		catch (Exception e) {
			return null;
		}
	}

	/**
	 *  @param req_type Request Type (enumerated)
	 */
	public void setReqType(REQ_TYPE req_type) {
		values.put("req_type", req_type.value());
	}

	/**
	 *  @param req_type Request Type (as a String)
	 */
	public void setReqType(String req_type) {
		setValue("req_type", req_type);
	}

	/**
	 *  @param req_type Request Type (integer value)
	 */
	public void setReqType(short req_type) {
		setValue("req_type", req_type);
	}

}
